In [28]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
def matrix_sum(n,m):
    D=[]
    E=[]
    for i in range(m*n):
        a=int(input("enter element :"))
        D.append(a)
    for j in range(m*n):
        b=int(input("enter your element: "))
        E.append(b)
    matrix1=np.array(D).reshape(m,n)
    matrix2= np.array(E).reshape(m,n)
    print("your matrix1 :\n", matrix1 )
    print("your matrix2 :\n", matrix2)
    print(" sum of two matrix :\n ")
    return matrix1 + matrix2
              
    
        
              
    
    

In [29]:
matrix_sum(3,3)

enter element :1
enter element :2
enter element :3
enter element :4
enter element :5
enter element :6
enter element :7
enter element :8
enter element :9
enter your element: 1
enter your element: 2
enter your element: 3
enter your element: 4
enter your element: 5
enter your element: 6
enter your element: 7
enter your element: 8
enter your element: 9
your matrix1 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
your matrix2 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [81]:
# 2. Write a Python Program to Multiply Two Matrices?
import numpy as np
def matrix_mutiply(n,m):
    D=[]
    E=[]
    for i in range(m*n):
        a=int(input("enter element :"))
        D.append(a)
    for j in range(m*n):
        b=int(input("enter your element: "))
        E.append(b)
    A=np.array(D).reshape(n,m)
    B= np.array(E).reshape(m,n)
    result = [[sum(a* b for a, b in zip(A_row, B_col))
                        for B_col in zip(*B)]
                                for A_row in A]
    for r in result:
        print(r)
                


In [82]:
matrix_mutiply(3,3)

enter element :1
enter element :2
enter element :3
enter element :4
enter element :5
enter element :6
enter element :7
enter element :8
enter element :9
enter your element: 1
enter your element: 2
enter your element: 3
enter your element: 4
enter your element: 5
enter your element: 6
enter your element: 7
enter your element: 8
enter your element: 9
[30, 36, 42]
[66, 81, 96]
[102, 126, 150]


In [84]:
# 3. Write a Python Program to Transpose a Matrix?
import numpy as np

def matrix_transpose(n,m):
    D=[]
    for i in range(m*n):
        a=int(input("enter element :"))
        D.append(a)
    matrix=np.array(D).reshape(m,n)
    return matrix.T

In [69]:
#4. Write a Python Program to Sort Words in Alphabetic Order?


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
def sort_word(input1):
    if type(input1)==str:
        b=input1.split(" ")
        b.sort()
        for i in b:
            print(i)
    else:
        pass
    return "string sorted"
    

        

In [108]:
sort_word("this is a book ")


a
book
is
this


'string sorted'

In [34]:
#5. Write a Python Program to Remove Punctuation From a String?
def removep():
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    a=input("enter your string")
    for i in a:
        for j in punc:
            if i==j:
                a=a.replace( i,"")
    return a
            


In [36]:
removep()

enter your stringghdthfsn32/?][[()fdgh43_


'ghdthfsn32fdgh43'

.
?
!
,
:
;
_
-
()
[]
/
""
''
....


In [31]:
a= "ran[]"
for i in a :
    print(i)

r
a
n
[
]
